import { NextRequest, NextResponse } from "next/server";

export const allProducts = [
  {
    id: 1,
    title: "Bunka N695 Stainless Steel 165mm",
    srcUrl: "/images/pic1.png",
    gallery: ["/images/pic1.png"],
    price: 1000000,
    discount: { amount: 0, percentage: 1 },
    rating: 4.8,
    stock: 10,
    desc: "Pisau Bunka premium berbahan N695 stainless steel dengan ketajaman tinggi dan presisi maksimal untuk kebutuhan dapur profesional.",
    specification: {
      "Blade Shape": "Bunka",
      "Steel Type": "N695 Stainless Steel",
      "Blade Length": "165mm",
      "Blade Height": "45mm",
      "Spine Thickness": "2.5mm",
      "Handle Length": "130mm",
      "Handle Type": "Wa Handle",
      "Handle Materials": "Teakwood",
    },
  },
  {
    id: 2,
    title: "Pisau Dapur Slicer HSS 210mm Kurouchi Finish",
    srcUrl: "/images/pic2.png",
    gallery: ["/images/pic2.png"],
    price: 800000,
    discount: { amount: 0, percentage: 1 },
    rating: 4.6,
    stock: 15,
    desc: "Pisau slicer berbahan High Speed Steel dengan finishing kurouchi, cocok untuk slicing daging dan ikan dengan hasil presisi.",
    specification: {
      "Blade Shape": "Slicer",
      "Steel Type": "High Speed Steel",
      "Blade Length": "210mm",
      "Blade Height": "38mm",
      "Spine Thickness": "2.3mm",
      "Handle Length": "135mm",
      "Handle Type": "Wa Handle",
      "Handle Materials": "Rosewood",
    },
  },
  {
    id: 3,
    title: "Pisau Dapur Gyuto 210mm Nashiji Finish",
    srcUrl: "/images/pic3.png",
    gallery: ["/images/pic3.png"],
    price: 850000,
    discount: { amount: 0, percentage: 1 },
    rating: 4.7,
    stock: 8,
    desc: "Gyuto serbaguna dengan finishing Nashiji, ideal untuk memotong, mengiris, dan mencincang berbagai bahan makanan.",
    specification: {
      "Blade Shape": "Gyuto",
      "Steel Type": "High Carbon Steel",
      "Blade Length": "210mm",
      "Blade Height": "48mm",
      "Spine Thickness": "2.4mm",
      "Handle Length": "130mm",
      "Handle Type": "Wa Handle",
      "Handle Materials": "Ebony",
    },
  },
  {
    id: 4,
    title: "Pisau Dapur Bunka HSS 165mm",
    srcUrl: "/images/pic4.png",
    gallery: ["/images/pic4.png"],
    price: 750000,
    discount: { amount: 0, percentage: 1 },
    rating: 4.5,
    stock: 12,
    desc: "Bunka berbahan HSS dengan ketahanan tinggi dan performa cutting yang konsisten untuk kebutuhan dapur harian.",
    specification: {
      "Blade Shape": "Bunka",
      "Steel Type": "High Speed Steel",
      "Blade Length": "165mm",
      "Blade Height": "45mm",
      "Spine Thickness": "2.2mm",
      "Handle Length": "125mm",
      "Handle Type": "Wa Handle",
      "Handle Materials": "Teakwood",
    },
  },
  {
    id: 5,
    title: "Deba 165mm High Speed Steel",
    srcUrl: "/images/pic5.png",
    gallery: ["/images/pic5.png"],
    price: 900000,
    discount: { amount: 0, percentage: 1 },
    rating: 5.0,
    stock: 6,
    desc: "Pisau Deba khusus untuk fillet ikan dan potongan presisi dengan mata pisau tebal dan kuat.",
    specification: {
      "Blade Shape": "Deba",
      "Steel Type": "High Speed Steel",
      "Blade Length": "165mm",
      "Blade Height": "50mm",
      "Spine Thickness": "4mm",
      "Handle Length": "135mm",
      "Handle Type": "Wa Handle",
      "Handle Materials": "Rosewood",
    },
  },
  {
    id: 6,
    title: "Pisau Dapur Gyuto 240mm Amboyna Blue Resin Handle",
    srcUrl: "/images/pic6.png",
    gallery: ["/images/pic6.png"],
    price: 2500000,
    discount: { amount: 0, percentage: 1 },
    rating: 4.9,
    stock: 5,
    desc: "Gyuto premium dengan handle Amboyna Blue Resin eksklusif dan performa tajam luar biasa.",
    specification: {
      "Blade Shape": "Gyuto",
      "Steel Type": "N690 Stainless Steel",
      "Blade Length": "240mm",
      "Blade Height": "52mm",
      "Spine Thickness": "2.6mm",
      "Handle Length": "140mm",
      "Handle Type": "Custom Resin Handle",
      "Handle Materials": "Amboyna & Resin",
    },
  },
  {
    id: 7,
    title: "Tactical Knife N690co Cobalt Blade Material",
    srcUrl: "/images/pic7.png",
    gallery: ["/images/pic7.png"],
    price: 1300000,
    discount: { amount: 0, percentage: 1 },
    rating: 4.8,
    stock: 4,
    desc: "Pisau tactical berbahan N690co cobalt dengan daya tahan tinggi dan performa cutting maksimal untuk outdoor.",
    specification: {
      "Blade Shape": "Tactical",
      "Steel Type": "N690co Cobalt",
      "Blade Length": "180mm",
      "Blade Height": "35mm",
      "Spine Thickness": "3.5mm",
      "Handle Length": "130mm",
      "Handle Type": "Full Tang",
      "Handle Materials": "G10",
    },
  },
  {
    id: 8,
    title: "Gyuto HSS 210 with Dyed Alder Wood Handle",
    srcUrl: "/images/pic8.png",
    gallery: ["/images/pic8.png"],
    price: 1800000,
    discount: { amount: 0, percentage: 1 },
    rating: 4.7,
    stock: 7,
    desc: "Gyuto HSS 210mm dengan handle alder wood dyed eksklusif dan keseimbangan sempurna.",
    specification: {
      "Blade Shape": "Gyuto",
      "Steel Type": "High Speed Steel",
      "Blade Length": "210mm",
      "Blade Height": "50mm",
      "Spine Thickness": "2.5mm",
      "Handle Length": "135mm",
      "Handle Type": "Wa Handle",
      "Handle Materials": "Dyed Alder Wood",
    },
  },
];

export const GET = async (req: NextRequest) => {
  const { searchParams } = new URL(req.url);
  const page = Number(searchParams.get("page") || 1);
  const limit = Number(searchParams.get("limit") || 8);

  const start = (page - 1) * limit;
  const end = start + limit;
  const data = allProducts.slice(start, end);

  return NextResponse.json({
    data,
    total: allProducts.length,
    page,
    totalPages: Math.ceil(allProducts.length / limit),
  });
};
