import type { Metadata, Viewport } from "next";
import "@/styles/globals.css";
import { satoshi } from "@/styles/fonts";
import RootClientLayout from "./RootClientLayout";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Pisaupedia",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={satoshi.className}>
        <RootClientLayout>{children}</RootClientLayout>
        <Footer />
      </body>
    </html>
  );
}